### ISSUE TITLE
sunxi_disp_ioctl.h missing

### ISSUE THREAD

**Issue by fieldOfView** [digitalhack/openFrameworks#4]
Looks like you may have forgotten to include 'sunxi_disp_ioctl.h' in the new repo:
https://github.com/digitalhack/pcDuino-openFrameworks/blob/pcDuino-dev/libs/openFrameworks/app/sunxi_disp_ioctl.h

**Comment by fieldOfView** [comment]
See https://github.com/digitalhack/openFrameworks/pull/5

**Comment by digitalhack** [comment]
I ended up changing the location for sunxi_disp_ioctl.h to libs/sunxi/include.

**Comment by fieldOfView** [comment]
Much better!
